Repository OpenCerts/opencerts-website, pull requests merged in 2019-05, with the labels that each got.

#220 Fixed navigation error for sidebar in mobile view.
  src/components/CertificateTemplates/utils/MultiCertificateRenderer.js
Labels: bug

#237 Adding new custom-templates, and registry identity for ITE.
  package-lock.json
  package.json
  src/components/CertificateTemplates/tlds/sg/edu/index.js
  src/components/CertificateTemplates/tlds/sg/edu/ite/ITE-2019-COM-CERT-COM-NIEC1/ITE_TEST-2019-CERT-COM-NIEC1.opencert
  src/components/CertificateTemplates/tlds/sg/edu/ite/ITE-2019-COM-CERT-COM-NIEC1/certificate.js
  src/components/CertificateTemplates/tlds/sg/edu/ite/ITE-2019-COM-CERT-COM-NIEC1/index.js
  src/components/CertificateTemplates/tlds/sg/edu/ite/ITE-2019-COM-CERT-COM-NIEC1/integration_2019.spec.js
  src/components/CertificateTemplates/tlds/sg/edu/ite/ITE-2019-COM-CERT-COM1/ITE_TEST-2019-COM-CERT-COM1.opencert
  src/components/CertificateTemplates/tlds/sg/edu/ite/ITE-2019-COM-CERT-COM1/certificate.js
  src/components/CertificateTemplates/tlds/sg/edu/ite/ITE-2019-COM-CERT-COM1/index.js
  src/components/CertificateTemplates/tlds/sg/edu/ite/ITE-2019-COM-CERT-COM1/integration_2019.spec.js
  src/components/CertificateTemplates/tlds/sg/edu/ite/ITE-2019-FUL-CERT-FULL-NIEC1/ITE_TEST-2019-CERT-FULL-NIEC1.opencert
  src/components/CertificateTemplates/tlds/sg/edu/ite/ITE-2019-FUL-CERT-FULL-NIEC1/certificate.js
  src/components/CertificateTemplates/tlds/sg/edu/ite/ITE-2019-FUL-CERT-FULL-NIEC1/index.js
  src/components/CertificateTemplates/tlds/sg/edu/ite/ITE-2019-FUL-CERT-FULL-NIEC1/integration_2019.spec.js
  src/components/CertificateTemplates/tlds/sg/edu/ite/ITE-2019-FUL-CERT-FULL1/ITE_TEST-2019-CERT-FULL1.opencert
  src/components/CertificateTemplates/tlds/sg/edu/ite/ITE-2019-FUL-CERT-FULL1/certificate.js
  src/components/CertificateTemplates/tlds/sg/edu/ite/ITE-2019-FUL-CERT-FULL1/index.js
  src/components/CertificateTemplates/tlds/sg/edu/ite/ITE-2019-FUL-CERT-FULL1/integration_2019.spec.js
  src/components/CertificateTemplates/tlds/sg/edu/ite/common/certificate.js
  src/components/CertificateTemplates/tlds/sg/edu/ite/common/images.js
  src/components/CertificateTemplates/tlds/sg/edu/ite/common/index.js
  src/components/CertificateTemplates/tlds/sg/edu/ite/index.js
  static/registry.json
Labels: new template

#273 UI Changes in SF_SOA_MF_001,SOA-001,SOA-002
  src/components/CertificateTemplates/tlds/sg/gov/ssg-wsg/SF_SOA_MF_01/certificate.js
  src/components/CertificateTemplates/tlds/sg/gov/ssg-wsg/SF_SOA_MF_01/integration.spec.js
  src/components/CertificateTemplates/tlds/sg/gov/ssg-wsg/SOA-001/certificate.js
  src/components/CertificateTemplates/tlds/sg/gov/ssg-wsg/SOA-002/certificate.js
  src/components/CertificateTemplates/tlds/sg/gov/ssg-wsg/SOA-002/integration.spec.js
  src/components/CertificateTemplates/tlds/sg/gov/ssg-wsg/common/functions.js
Labels: Ready to merge

#286 Soften the warning for unregistered institutes
  package-lock.json
  src/components/CertificateDropZone/CertificateDropZone.js
  src/components/CertificateTemplates/Default/integration.spec.js
  src/components/CertificateVerifyBlock/CertificateVerifyBlock.js
  src/components/CertificateVerifyBlock/DetailedCertificateVerifyBlock.js
  src/components/CertificateVerifyBlock/__snapshots__/DetailedCertificateVerifyBlock.test.js.snap
  src/sagas/certificate.js
Labels: Review Me
