Repository OpenCerts/opencerts-website, pull requests merged in 2019-04, with the labels that each got.

#132 Fix/frameless navigation
  src/components/CertificateTemplates/utils/MultiCertificateRenderer.js
  src/components/CertificateVerifyBlock/CertificateVerifyBlock.js
  src/components/Layout/NavigationBar/NavigationBar.js
  src/components/UI/Drawer/drawer.js
  src/components/UI/Drawer/drawer.scss
  src/components/UI/Drawer/index.js
  src/components/certificateViewer.scss
Labels: enhancement

#149 update pr template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: new template

#143 Updated url
  src/config/index.js
  src/services/email/email.test.js
  src/services/email/index.js
Labels: Review Me

#161 Added ropsten emial api
  package-lock.json
  src/config/index.js
Labels: Review Me

#160 Added New Templates for SSG (SOA, QUAL & TRANS Certs)
  README.md
  package-lock.json
  src/components/CertificateTemplates/legacy.js
  src/components/CertificateTemplates/tlds/sg/gov/index.js
  src/components/CertificateTemplates/tlds/sg/gov/ssg-wsg/FQ-001/FQ-001_S0000000A_18Q000000012381.OPENCERT
  src/components/CertificateTemplates/tlds/sg/gov/ssg-wsg/FQ-001/certificate.js
  src/components/CertificateTemplates/tlds/sg/gov/ssg-wsg/FQ-001/index.js
  src/components/CertificateTemplates/tlds/sg/gov/ssg-wsg/FQ-001/integration.spec.js
  src/components/CertificateTemplates/tlds/sg/gov/ssg-wsg/SOA-001/SOA-001_S0000000A_180000000226558.OPENCERT
  src/components/CertificateTemplates/tlds/sg/gov/ssg-wsg/SOA-001/certificate.js
  src/components/CertificateTemplates/tlds/sg/gov/ssg-wsg/SOA-001/index.js
  src/components/CertificateTemplates/tlds/sg/gov/ssg-wsg/SOA-001/integration.spec.js
  src/components/CertificateTemplates/tlds/sg/gov/ssg-wsg/Trans/Trans_S0000000A_18T000000012381.OPENCERT
  src/components/CertificateTemplates/tlds/sg/gov/ssg-wsg/Trans/certificate.js
  src/components/CertificateTemplates/tlds/sg/gov/ssg-wsg/Trans/index.js
  src/components/CertificateTemplates/tlds/sg/gov/ssg-wsg/Trans/integration.spec.js
  src/components/CertificateTemplates/tlds/sg/gov/ssg-wsg/common/functions.js
  src/components/CertificateTemplates/tlds/sg/gov/ssg-wsg/common/images.js
  src/components/CertificateTemplates/tlds/sg/gov/ssg-wsg/common/index.js
  src/components/CertificateTemplates/tlds/sg/gov/ssg-wsg/index.js
  static/registry.json
Labels: new template

#171 Moving handleObfuscation and certificate into MultiCertRenderer
  pages/frameless-viewer.js
  src/components/CertificateTemplates/Default/index.js
  src/components/CertificateTemplates/example/2019-Feb-ExampleTemplate/index.js
  src/components/CertificateTemplates/tlds/sg/edu/np/NP-AA1996-MAIN/index.js
  src/components/CertificateTemplates/tlds/sg/edu/np/NP-AA2018-BMS(CLT)/index.js
  src/components/CertificateTemplates/tlds/sg/edu/np/NP-AA2018-DPP/index.js
  src/components/CertificateTemplates/tlds/sg/edu/np/NP-AA2018-ECH/index.js
  src/components/CertificateTemplates/tlds/sg/edu/np/NP-AA2018-LDH/index.js
  src/components/CertificateTemplates/tlds/sg/edu/np/NP-AA2018-MAIN/index.js
  src/components/CertificateTemplates/tlds/sg/edu/np/NP-AA2018-OPTION/index.js
  src/components/CertificateTemplates/tlds/sg/edu/np/NP-AA2018-PHARM/index.js
  src/components/CertificateTemplates/tlds/sg/edu/np/NP-AA2019-NIEC/index.js
  src/components/CertificateTemplates/tlds/sg/edu/np/NP-AA2019-OPT-NIEC/index.js
  src/components/CertificateTemplates/tlds/sg/edu/np/NP-CET2019-PDPMAIN/index.js
  src/components/CertificateTemplates/tlds/sg/edu/np/NP-CET2019-PTDMAIN/index.js
  src/components/CertificateTemplates/tlds/sg/edu/np/NP-CET2019-SDCGN/index.js
  src/components/CertificateTemplates/tlds/sg/edu/np/NP-CET2019-SDPCN/index.js
  src/components/CertificateTemplates/tlds/sg/edu/singaporetech/2018-certificate/index.js
  src/components/CertificateTemplates/tlds/sg/gov/seab/SOR_GCEO/index.js
  src/components/CertificateTemplates/tlds/sg/gov/ssg-wsg/FQ-001/index.js
  src/components/CertificateTemplates/tlds/sg/gov/ssg-wsg/FQ-002/index.js
  src/components/CertificateTemplates/tlds/sg/gov/ssg-wsg/FQ-004/index.js
  src/components/CertificateTemplates/tlds/sg/gov/ssg-wsg/FQ-005/index.js
  src/components/CertificateTemplates/tlds/sg/gov/ssg-wsg/FQ-006/index.js
  src/components/CertificateTemplates/tlds/sg/gov/ssg-wsg/QUAL_Reprint/index.js
  src/components/CertificateTemplates/tlds/sg/gov/ssg-wsg/SF_FQ_001/index.js
  src/components/CertificateTemplates/tlds/sg/gov/ssg-wsg/SF_FQ_002/index.js
  src/components/CertificateTemplates/tlds/sg/gov/ssg-wsg/SF_FQ_004/index.js
  src/components/CertificateTemplates/tlds/sg/gov/ssg-wsg/SF_SOA_IT_001/index.js
  src/components/CertificateTemplates/tlds/sg/gov/ssg-wsg/SF_SOA_MF_01/index.js
  src/components/CertificateTemplates/tlds/sg/gov/ssg-wsg/SOA-001/index.js
  src/components/CertificateTemplates/tlds/sg/gov/ssg-wsg/SOA-002/index.js
  src/components/CertificateTemplates/tlds/sg/gov/ssg-wsg/SOA-003/index.js
  src/components/CertificateTemplates/tlds/sg/gov/ssg-wsg/SOA-IT-001/index.js
  src/components/CertificateTemplates/tlds/sg/gov/ssg-wsg/SOA-MF-01/index.js
  src/components/CertificateTemplates/tlds/sg/gov/ssg-wsg/Trans/index.js
  src/components/CertificateTemplates/tlds/sg/gov/tech/2018-OpenCertsAssociate/index.js
  src/components/CertificateTemplates/tlds/sg/gov/tech/2019-OpenCertsAssociate/index.js
  src/components/CertificateTemplates/utils/MultiCertificateRenderer.js
  src/components/CertificateViewer.js
  src/components/FramelessViewer/FramelessCertificateViewer.js
  src/components/FramelessViewer/FramelessViewerPageContainer.js
  src/components/FramelessViewer/NP_CERT_FT_MAIN_2018.opencert
  src/components/FramelessViewer/integration-frameless.spec.js
  src/components/ViewerPageContainer.js
  src/reducers/certificate.js
  src/reducers/certificate.test.js
Labels: Review Me

#211 Fixed template generated by cli
  src/components/CertificateTemplates/example/2019-Feb-ExampleTemplate/index.js
Labels: Review Me

#212 Running Sonar on master & Excluding coverage for custom templates
  jest.config.js
  package-lock.json
  scripts/sonar-runner.sh
  sonar-project.properties
Labels: Review Me

#145 fix template background and alignment
  src/components/CertificateTemplates/tlds/sg/edu/index.js
  src/components/CertificateTemplates/tlds/sg/edu/nyp/NYP-Main/certificate.js
  src/components/CertificateTemplates/tlds/sg/edu/nyp/NYP-Main/images.js
  src/components/CertificateTemplates/tlds/sg/edu/nyp/NYP-Main/index.js
  src/components/CertificateTemplates/tlds/sg/edu/nyp/NYP-Main/integration.spec.js
  src/components/CertificateTemplates/tlds/sg/edu/nyp/NYP-Main/test1.opencert
  src/components/CertificateTemplates/tlds/sg/edu/nyp/index.js
  static/registry.json
Labels: new template
