Repository OpenCerts/opencerts-website, pull requests merged in 2019-07, with the labels that each got.

#347 fix(test): Removed integration test for registry
  src/components/integration-registry.spec.js
Labels: Review Me, bug

#331 fix(Error): priority of displaying error messages
  package-lock.json
  src/components/CertificateDropZone/CertificateDropZone.js
  src/components/CertificateDropZone/CertificateDropZoneContainer.js
  src/components/CertificateDropZone/Views/UnverifiedView.js
  src/components/UI/Drawer/drawer.scss
  src/reducers/certificate.js
  src/sagas/certificate.js
  src/sagas/certificate.test.js
  src/sagas/sagatests/integration-invalidstore.spec.js
  src/sagas/sagatests/integration-merkle.spec.js
  src/sagas/sagatests/integration-multiple-invalidstore.spec.js
  src/sagas/sagatests/integration-tampered.spec.js
  src/sagas/sagatests/integration-unissued.spec.js
  src/sagas/sagatests/invalidstore.opencert
  src/sagas/sagatests/multipleinvalidstores.opencert
  src/sagas/sagatests/tampered.opencert
  src/sagas/sagatests/unissued.opencert
  src/sagas/sagatests/wrong-merkle.opencert
Labels: Review Me

#325 feat(page): Added collaborate page and linked in navigation bar
  next.config.js
  package-lock.json
  pages/collaborate.js
  src/components/Collaborate/CollaboratePageContainer.js
  src/components/Collaborate/collaborators.json
  src/components/Layout/FooterBar.js
  src/components/Layout/NavigationBar/NavigationBar.js
  src/components/Layout/footer.scss
  src/components/RegistryPageContainer.js
  src/components/UI/Card/__snapshots__/card.test.js.snap
  src/components/UI/Card/card.js
  src/components/UI/Card/card.scss
  src/components/UI/Card/card.test.js
  src/components/registry.scss
  static/images/collaborate/ACCREDIFY_logo.png
  static/images/collaborate/EDUFIED_logo.png
  static/images/collaborate/NEXTID_logo.png
Labels: Review Me, Topic: Frontend/UI
