Repository OpenCerts/opencerts-website, pull requests merged in 2019-06, with the labels that each got.

#302 TP part-time templates update - part 1
  src/components/CertificateTemplates/tlds/sg/edu/tp/common/certificateBody.js
  src/components/CertificateTemplates/tlds/sg/edu/tp/common/certificateHeader.js
  src/components/CertificateTemplates/tlds/sg/edu/tp/common/certificateNameSection.js
  src/components/CertificateTemplates/tlds/sg/edu/tp/common/certificateSupporter.js
  src/components/CertificateTemplates/tlds/sg/edu/tp/common/images.js
  src/components/CertificateTemplates/tlds/sg/edu/tp/common/partTimeExamResults.js
  src/components/CertificateTemplates/tlds/sg/edu/tp/common/partTimeGradingScheme.js
  src/components/CertificateTemplates/tlds/sg/edu/tp/common/partTimeSubjectGrades.js
  src/components/CertificateTemplates/tlds/sg/edu/tp/common/transcriptHeader.js
  src/components/CertificateTemplates/tlds/sg/edu/tp/ftdipniec/NiecTranscriptHeader.js
  src/components/CertificateTemplates/tlds/sg/edu/tp/ftdipniec/certificateHeader.js
  src/components/CertificateTemplates/tlds/sg/edu/tp/ftdipniec/test.spec.js
  src/components/CertificateTemplates/tlds/sg/edu/tp/ftpfp/index.js
  src/components/CertificateTemplates/tlds/sg/edu/tp/ftpfp/test.spec.js
  src/components/CertificateTemplates/tlds/sg/edu/tp/ftpfp/transcriptHeader.js
  src/components/CertificateTemplates/tlds/sg/edu/tp/ptdip/index.js
  src/components/CertificateTemplates/tlds/sg/edu/tp/ptdip/sample.opencert
  src/components/CertificateTemplates/tlds/sg/edu/tp/ptdip/test.spec.js
  src/components/CertificateTemplates/tlds/sg/edu/tp/ptmc/certificateBody.js
  src/components/CertificateTemplates/tlds/sg/edu/tp/ptmc/sample.opencert
  src/components/CertificateTemplates/tlds/sg/edu/tp/ptmc/test.spec.js
  src/components/CertificateTemplates/tlds/sg/edu/tp/ptpdc/sample.opencert
  src/components/CertificateTemplates/tlds/sg/edu/tp/ptpdc/test.spec.js
Labels: Ready to merge

#304 TP part-time templates update - part 3
  src/components/CertificateTemplates/tlds/sg/edu/tp/index.js
  src/components/CertificateTemplates/tlds/sg/edu/tp/ptpostdip/index.js
  src/components/CertificateTemplates/tlds/sg/edu/tp/ptpostdip/sample.opencert
  src/components/CertificateTemplates/tlds/sg/edu/tp/ptpostdip/test.spec.js
Labels: Ready to merge

#305 TP part-time templates update - part 4
  src/components/CertificateTemplates/tlds/sg/edu/tp/index.js
  src/components/CertificateTemplates/tlds/sg/edu/tp/ptdip_certis/certificate.js
  src/components/CertificateTemplates/tlds/sg/edu/tp/ptdip_certis/index.js
  src/components/CertificateTemplates/tlds/sg/edu/tp/ptdip_certis/sample.opencert
  src/components/CertificateTemplates/tlds/sg/edu/tp/ptdip_certis/test.spec.js
Labels: Ready to merge

#306 TP part-time templates update - part 5
  src/components/CertificateTemplates/tlds/sg/edu/tp/index.js
  src/components/CertificateTemplates/tlds/sg/edu/tp/ptdipdpss/certificate.js
  src/components/CertificateTemplates/tlds/sg/edu/tp/ptdipdpss/index.js
  src/components/CertificateTemplates/tlds/sg/edu/tp/ptdipdpss/sample.opencert
  src/components/CertificateTemplates/tlds/sg/edu/tp/ptdipdpss/test.spec.js
Labels: Ready to merge

#307 TP part-time templates update - part 6
  src/components/CertificateTemplates/tlds/sg/edu/tp/index.js
  src/components/CertificateTemplates/tlds/sg/edu/tp/ptsd_bcaa/certificate.js
  src/components/CertificateTemplates/tlds/sg/edu/tp/ptsd_bcaa/index.js
  src/components/CertificateTemplates/tlds/sg/edu/tp/ptsd_bcaa/sample.opencert
  src/components/CertificateTemplates/tlds/sg/edu/tp/ptsd_bcaa/test.spec.js
Labels: Ready to merge

#308 TP part-time templates update - part 7
  src/components/CertificateTemplates/tlds/sg/edu/tp/index.js
  src/components/CertificateTemplates/tlds/sg/edu/tp/ptsd_mha/certificate.js
  src/components/CertificateTemplates/tlds/sg/edu/tp/ptsd_mha/index.js
  src/components/CertificateTemplates/tlds/sg/edu/tp/ptsd_mha/sample.opencert
  src/components/CertificateTemplates/tlds/sg/edu/tp/ptsd_mha/test.spec.js
Labels: Ready to merge

#309 TP part-time templates update - part 8
  src/components/CertificateTemplates/tlds/sg/edu/tp/index.js
  src/components/CertificateTemplates/tlds/sg/edu/tp/ptsd_np/certificate.js
  src/components/CertificateTemplates/tlds/sg/edu/tp/ptsd_np/certificateBody.js
  src/components/CertificateTemplates/tlds/sg/edu/tp/ptsd_np/certificateFooter.js
  src/components/CertificateTemplates/tlds/sg/edu/tp/ptsd_np/certificateHeader.js
  src/components/CertificateTemplates/tlds/sg/edu/tp/ptsd_np/index.js
  src/components/CertificateTemplates/tlds/sg/edu/tp/ptsd_np/sample.opencert
  src/components/CertificateTemplates/tlds/sg/edu/tp/ptsd_np/test.spec.js
Labels: Ready to merge

#310 TP part-time templates update - part 9
  src/components/CertificateTemplates/tlds/sg/edu/tp/index.js
  src/components/CertificateTemplates/tlds/sg/edu/tp/ptsd_sit/certificate.js
  src/components/CertificateTemplates/tlds/sg/edu/tp/ptsd_sit/index.js
  src/components/CertificateTemplates/tlds/sg/edu/tp/ptsd_sit/sample.opencert
  src/components/CertificateTemplates/tlds/sg/edu/tp/ptsd_sit/test.spec.js
Labels: Ready to merge

#311 TP part-time templates update - part 10
  src/components/CertificateTemplates/tlds/sg/edu/tp/index.js
  src/components/CertificateTemplates/tlds/sg/edu/tp/ptsd_smu/certificate.js
  src/components/CertificateTemplates/tlds/sg/edu/tp/ptsd_smu/index.js
  src/components/CertificateTemplates/tlds/sg/edu/tp/ptsd_smu/sample.opencert
  src/components/CertificateTemplates/tlds/sg/edu/tp/ptsd_smu/test.spec.js
Labels: Ready to merge

#312 TP part-time templates update - part 11
  src/components/CertificateTemplates/tlds/sg/edu/tp/index.js
  src/components/CertificateTemplates/tlds/sg/edu/tp/ptsd_suss/certificate.js
  src/components/CertificateTemplates/tlds/sg/edu/tp/ptsd_suss/index.js
  src/components/CertificateTemplates/tlds/sg/edu/tp/ptsd_suss/sample.opencert
  src/components/CertificateTemplates/tlds/sg/edu/tp/ptsd_suss/test.spec.js
Labels: Ready to merge

#313 TP part-time templates update - part 12
  src/components/CertificateTemplates/tlds/sg/edu/tp/index.js
  src/components/CertificateTemplates/tlds/sg/edu/tp/ptsdoh/certificate.js
  src/components/CertificateTemplates/tlds/sg/edu/tp/ptsdoh/index.js
  src/components/CertificateTemplates/tlds/sg/edu/tp/ptsdoh/sample.opencert
  src/components/CertificateTemplates/tlds/sg/edu/tp/ptsdoh/test.spec.js
Labels: Ready to merge

#301 Feat/demo
  package-lock.json
  scripts/addNewTemplate.utils.test.js
  src/components/CertificateTemplates/example/2019-Feb-ExampleTemplate/certificate.js
  src/components/CertificateTemplates/example/2019-Feb-ExampleTemplate/index.js
  src/components/CertificateTemplates/example/2019-Feb-ExampleTemplate/resources.js
  src/components/CertificateTemplates/example/Demo-CertTemplate/DEMO_2019.opencert
  src/components/CertificateTemplates/legacy.js
  src/components/CertificateTemplates/tlds/sg/gov/tech/2019-OpenCertsAssociate/certificate.js
  src/components/CertificateTemplates/tlds/sg/gov/tech/2019-OpenCertsAssociate/index.js
  src/components/CertificateTemplates/tlds/sg/gov/tech/2019-OpenCertsAssociate/resources.js
  src/components/CertificateTemplates/tlds/sg/gov/tech/Govtech-Demo-Cert/Main-Demo.json
  src/components/CertificateTemplates/tlds/sg/gov/tech/Govtech-Demo-Cert/Ropsten-Demo.json
  src/components/CertificateTemplates/tlds/sg/gov/tech/Govtech-Demo-Cert/certificate.js
  src/components/CertificateTemplates/tlds/sg/gov/tech/Govtech-Demo-Cert/common/backgrounds.js
  src/components/CertificateTemplates/tlds/sg/gov/tech/Govtech-Demo-Cert/common/demoStyles.scss
  src/components/CertificateTemplates/tlds/sg/gov/tech/Govtech-Demo-Cert/common/functions.js
  src/components/CertificateTemplates/tlds/sg/gov/tech/Govtech-Demo-Cert/common/index.js
  src/components/CertificateTemplates/tlds/sg/gov/tech/Govtech-Demo-Cert/index.js
  src/components/CertificateTemplates/tlds/sg/gov/tech/Govtech-Demo-Cert/media.js
  src/components/CertificateTemplates/tlds/sg/gov/tech/Govtech-Demo-Cert/transcript.js
  src/components/CertificateTemplates/tlds/sg/gov/tech/index.js
  src/components/CertificateTemplates/tlds/sg/index.js
  src/components/CertificateVerifyBlock/integration.spec.js
  src/components/HomePageContent/DropZoneSection.js
  src/components/HomePageContent/PartnersSection.js
  src/components/HomePageContent/dropZoneSection.scss
  src/components/TemplateCommon/Privacy/ObfuscatableValue.js
  src/config/index.js
  src/constants/PartnerLogo.json
  src/styles/variables.scss
  static/images/dropzone/arrow.png
  static/images/dropzone/arrow2.png
  static/images/dropzone/arrow3.png
  static/images/dropzone/cert.png
  static/registry.json
  static/style.css
Labels: Ready to merge

#279 Added message passing capabilities for frameless-viewer for frameless-viewer
  .travis.yml
  package-lock.json
  package.json
  scripts/integration-headless.sh
  src/components/FramelessViewer/FramelessViewerPageContainer.js
  src/components/FramelessViewer/demo-iframe.html
  src/components/FramelessViewer/integration-frameless-iframe.spec.js
  src/components/FramelessViewer/integration-frameless-webview.spec.js
Labels: WIP

#316 added ga + fixed draggable
  src/components/HomePageContent/DropZoneSection.js
Labels: Ready to merge

#299 Feat/error boundry
  .eslintrc
  src/components/CertificateViewer.js
  src/components/ErrorBoundary.js
  src/components/ErrorBoundary.test.js
  src/components/Layout/footer.scss
  src/components/error.scss
  static/images/errorpage/error.png
  static/style.css
Labels: Ready to merge

#323 fix(iframe): Remove iframe header
  src/components/CertificateTemplates/utils/MultiCertificateRenderer.js
  src/components/FramelessViewer/FramelessViewerPageContainer.js
  src/components/certificateViewer.scss
Labels: Ready to merge

#320 feat(Template): Certificate template for GovTech GeekOut 2019
  scripts/addNewTemplate.utils.test.js
  src/components/CertificateTemplates/tlds/sg/gov/tech/2018-Geekout/certificate.js
  src/components/CertificateTemplates/tlds/sg/gov/tech/2018-Geekout/certificate.opencert
  src/components/CertificateTemplates/tlds/sg/gov/tech/2018-Geekout/index.js
  src/components/CertificateTemplates/tlds/sg/gov/tech/2018-Geekout/integration.spec.js
  src/components/CertificateTemplates/tlds/sg/gov/tech/2018-Geekout/styles.scss
  src/components/CertificateTemplates/tlds/sg/gov/tech/index.js
Labels: Review Me

#334 Fix Cert title & store address for ITE
  src/components/CertificateTemplates/tlds/sg/edu/ite/common/certificate.js
  src/components/CertificateTemplates/tlds/sg/edu/ite/common/index.js
  static/registry.json
Labels: Registry Application

#321 feat(Registry): new registry format
  src/components/RegistryPageContainer.js
  src/components/integration-registry.spec.js
  src/sagas/certificate.js
  static/images/SEAB_logo_crop.png
  static/images/SIT_logo.png
  static/images/SSG_logo.png
  static/registry.json
Labels: Ready to merge

#292 SEAB PSLE
  src/components/CertificateTemplates/tlds/sg/gov/seab/SOR_PSLE_1980_1981/SOR_ALL-1981_PSLE_01313F.opencert
  src/components/CertificateTemplates/tlds/sg/gov/seab/SOR_PSLE_1980_1981/index.js
  src/components/CertificateTemplates/tlds/sg/gov/seab/SOR_PSLE_1980_1981/integration.spec.js
  src/components/CertificateTemplates/tlds/sg/gov/seab/SOR_PSLE_1980_1981/sor.js
  src/components/CertificateTemplates/tlds/sg/gov/seab/SOR_PSLE_1982_1992/SOR_ALL-1992_PSLE_00197I.opencert
  src/components/CertificateTemplates/tlds/sg/gov/seab/SOR_PSLE_1982_1992/index.js
  src/components/CertificateTemplates/tlds/sg/gov/seab/SOR_PSLE_1982_1992/integration.spec.js
  src/components/CertificateTemplates/tlds/sg/gov/seab/SOR_PSLE_1982_1992/sor.js
  src/components/CertificateTemplates/tlds/sg/gov/seab/SOR_PSLE_1993_2012/SOR_ALL-1993_PSLE_01001C.opencert
  src/components/CertificateTemplates/tlds/sg/gov/seab/SOR_PSLE_1993_2012/index.js
  src/components/CertificateTemplates/tlds/sg/gov/seab/SOR_PSLE_1993_2012/integration.spec.js
  src/components/CertificateTemplates/tlds/sg/gov/seab/SOR_PSLE_1993_2012/sor.js
  src/components/CertificateTemplates/tlds/sg/gov/seab/SOR_PSLE_2013/SOR_ALL-2015_PSLE_00073E.opencert
  src/components/CertificateTemplates/tlds/sg/gov/seab/SOR_PSLE_2013/index.js
  src/components/CertificateTemplates/tlds/sg/gov/seab/SOR_PSLE_2013/integration.spec.js
  src/components/CertificateTemplates/tlds/sg/gov/seab/SOR_PSLE_2013/sor.js
  src/components/CertificateTemplates/tlds/sg/gov/seab/SOR_PSLE_before_1979/SOR_ALL-1978_PSLE_57540A.opencert
  src/components/CertificateTemplates/tlds/sg/gov/seab/SOR_PSLE_before_1979/index.js
  src/components/CertificateTemplates/tlds/sg/gov/seab/SOR_PSLE_before_1979/integration.spec.js
  src/components/CertificateTemplates/tlds/sg/gov/seab/SOR_PSLE_before_1979/sor.js
  src/components/CertificateTemplates/tlds/sg/gov/seab/common/explnotes_psle.js
  src/components/CertificateTemplates/tlds/sg/gov/seab/common/explnotes_psle_detail.js
  src/components/CertificateTemplates/tlds/sg/gov/seab/common/style.js
  src/components/CertificateTemplates/tlds/sg/gov/seab/common/template.js
  src/components/CertificateTemplates/tlds/sg/gov/seab/index.js
Labels: Ready to merge
